repos:
  # Python code formatting and import sorting
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # Linting
  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        additional_dependencies: [pylint]

  # Remove unused imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variables, --expand-star-imports, --remove-duplicate-keys]

  # Check for trailing whitespace and final newlines
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements

  # Custom hook to run tests
  - repo: local
    hooks:
      - id: run-tests
        name: Run all tests
        entry: bash -c 'cd /Users/ludwigw/Development/calendar && PYTHONPATH=. python -m unittest discover -s tests -p "test*.py" -v'
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
        additional_dependencies: []
